export class Profile {
    id: number;
    user_id: number;
    years_of_teaching_min: number;
    years_of_teaching_max: number;
    created_at: string;
    updated_at: string;
    preferred_age_range_4_7: number;
    preferred_age_range_7_10: number;
    preferred_age_range_10_14: number;
    strength_phonetic: number;
    strength_pronunciation: number;
    strength_tpr: number;
    strength_behavior_management: number;
    strength_early_childhood: number;
    strength_writing: number;
    strength_english_test_prep: number;
    strength_grammar_training: number;
    strength_conversation_training: number;
    strength_personalized_lesson: number;
    classroom_features_manipulatives: number;
    classroom_features_reward_system: number;
    classroom_features_educational_environment: number;
    classroom_features_class_notes: number;
    classroom_features_community_interaction: number;
    classroom_features_set_curriculum: number;
    classroom_features_homework: number;
    relevant_information: string;
}